{"error": {
  "code": 400,
  "context": "Test file ExDTest4.json",
  "details": [
    {
      "code": "JSONException",
      "message": "caught and rethrow from level: ",
      "param0": "",
      "template": "caught and rethrow from level: {0}"
    },
    {
      "code": "Exception",
      "message": "top level exception thrown by exception test when course string ran out"
    }
  ],
  "innerError": {},
  "stack": [
    "top level exception thrown by exception test when course string ran out",
    "    TestExceptions.java: callHigher: 122",
    "    TestExceptions.java: sampleMethod2: 75",
    "caught and rethrow from level: ",
    "    TestExceptions.java: sampleMethod2: 112",
    "    TestExceptions.java: callHigher: 129",
    "    TestExceptions.java: testExceptionStackTrace: 177"
  ]
}}