{"error": {
  "code": 400,
  "context": "Test file ExDTest3.json",
  "details": [
    {
      "code": "JSONException",
      "message": "caught and rethrow from level: 22",
      "param0": "22",
      "template": "caught and rethrow from level: {0}"
    },
    {
      "code": "JSONException",
      "message": "caught and rethrow from level: 2",
      "param0": "2",
      "template": "caught and rethrow from level: {0}"
    },
    {
      "code": "JSONException",
      "message": "caught and rethrow from level: ",
      "param0": "",
      "template": "caught and rethrow from level: {0}"
    },
    {
      "code": "Exception",
      "message": "top level exception thrown by exception test when course string ran out"
    }
  ],
  "innerError": {},
  "stack": [
    "top level exception thrown by exception test when course string ran out",
    "    TestExceptions.java: callHigher: 121",
    "    TestExceptions.java: sampleMethod2: 80",
    "caught and rethrow from level: ",
    "    TestExceptions.java: sampleMethod2: 111",
    "    TestExceptions.java: callHigher: 128",
    "    TestExceptions.java: sampleMethod2: 77",
    "caught and rethrow from level: 2",
    "    TestExceptions.java: sampleMethod2: 111",
    "    TestExceptions.java: callHigher: 128",
    "    TestExceptions.java: sampleMethod2: 74",
    "caught and rethrow from level: 22",
    "    TestExceptions.java: sampleMethod2: 111",
    "    TestExceptions.java: callHigher: 128",
    "    TestExceptions.java: sampleMethod1: 64",
    "    TestExceptions.java: callHigher: 125",
    "    TestExceptions.java: testExceptionStackTrace: 178"
  ]
}}