{"error": {
  "code": 400,
  "context": "Test file ExTest5.json",
  "details": [
    {
      "code": "JSONException",
      "message": "caught and rethrow from level: 3123123123",
      "param0": "3123123123",
      "template": "caught and rethrow from level: {0}"
    },
    {
      "code": "JSONException",
      "message": "caught and rethrow from level: 3123123",
      "param0": "3123123",
      "template": "caught and rethrow from level: {0}"
    },
    {
      "code": "JSONException",
      "message": "caught and rethrow from level: 3123",
      "param0": "3123",
      "template": "caught and rethrow from level: {0}"
    },
    {
      "code": "JSONException",
      "message": "caught and rethrow from level: 3",
      "param0": "3",
      "template": "caught and rethrow from level: {0}"
    },
    {
      "code": "Exception",
      "message": "top level exception thrown by exception test when course string ran out"
    }
  ],
  "innerError": {},
  "stack": [
    "top level exception thrown by exception test when course string ran out",
    "    TestExceptions.java: callHigher: 122",
    "    TestExceptions.java: sampleMethod3: 117",
    "    TestExceptions.java: callHigher: 132",
    "    TestExceptions.java: sampleMethod2: 84",
    "    (continued below)",
    "caught and rethrow from level: 3",
    "    TestExceptions.java: sampleMethod2: 112",
    "    TestExceptions.java: callHigher: 129",
    "    TestExceptions.java: sampleMethod1: 65",
    "    TestExceptions.java: callHigher: 126",
    "    TestExceptions.java: sampleMethod3: 117",
    "    TestExceptions.java: callHigher: 132",
    "    TestExceptions.java: sampleMethod2: 81",
    "    (continued below)",
    "caught and rethrow from level: 3123",
    "    TestExceptions.java: sampleMethod2: 112",
    "    TestExceptions.java: callHigher: 129",
    "    TestExceptions.java: sampleMethod1: 65",
    "    TestExceptions.java: callHigher: 126",
    "    TestExceptions.java: sampleMethod3: 117",
    "    TestExceptions.java: callHigher: 132",
    "    TestExceptions.java: sampleMethod2: 78",
    "    (continued below)",
    "caught and rethrow from level: 3123123",
    "    TestExceptions.java: sampleMethod2: 112",
    "    TestExceptions.java: callHigher: 129",
    "    TestExceptions.java: sampleMethod1: 65",
    "    TestExceptions.java: callHigher: 126",
    "    TestExceptions.java: sampleMethod3: 117",
    "    TestExceptions.java: callHigher: 132",
    "    TestExceptions.java: sampleMethod2: 75",
    "    (continued below)",
    "caught and rethrow from level: 3123123123",
    "    TestExceptions.java: sampleMethod2: 112",
    "    TestExceptions.java: callHigher: 129",
    "    TestExceptions.java: sampleMethod1: 65",
    "    TestExceptions.java: callHigher: 126",
    "    TestExceptions.java: testExceptionStackTrace: 177"
  ]
}}