{"error": {
  "code": 400,
  "context": "Test file ExTest4.json",
  "details": [
    {
      "code": "JSONException",
      "message": "caught and rethrow from level: ",
      "param0": "",
      "template": "caught and rethrow from level: {0}"
    },
    {
      "code": "Exception",
      "message": "top level exception thrown by exception test when course string ran out"
    }
  ],
  "innerError": {},
  "stack": [
    "top level exception thrown by exception test when course string ran out",
    "    TestExceptions.java: callHigher: 121",
    "    TestExceptions.java: sampleMethod2: 74",
    "    (continued below)",
    "caught and rethrow from level: ",
    "    TestExceptions.java: sampleMethod2: 111",
    "    TestExceptions.java: callHigher: 128",
    "    TestExceptions.java: testExceptionStackTrace: 178"
  ]
}}