{"error": {
  "code": 400,
  "context": "Test file ExTest4.json for course 2",
  "details": [
    {
      "code": "JSONException",
      "message": "caught and rethrow from level: ",
      "param0": "",
      "template": "caught and rethrow from level: {0}"
    },
    {
      "code": "Exception",
      "message": "top level exception thrown by exception test when course string ran out"
    }
  ],
  "innerError": {},
  "stack": [
    "top level exception thrown by exception test when course string ran out",
    "    TestExceptions.java: callHigher: 86",
    "    TestExceptions.java: sampleMethod2: 73",
    "    (continued below)",
    "caught and rethrow from level: ",
    "    TestExceptions.java: sampleMethod2: 76",
    "    TestExceptions.java: callHigher: 93",
    "    TestExceptions.java: runCourse: 146",
    "    TestExceptions.java: runTests: 39",
    "    TestRecorderText.java: parseArgsRunTests: 637",
    "    TestExceptions.java: main: 184"
  ]
}}